mod animation;
mod audio;
mod callback_game;
mod callback_query;
mod chat;
mod chat_invite_link;
mod chat_join_request;
mod chat_location;
mod chat_member;
mod chat_member_updated;
mod chat_permissions;
mod chat_photo;
mod chat_shared;
mod chosen_inline_result;
mod contact;
mod dice;
mod document;
mod encrypted_credentials;
mod encrypted_passport_element;
mod file;
mod forum_topic_closed;
mod forum_topic_created;
mod forum_topic_edited;
mod forum_topic_reopened;
mod game;
mod general_forum_topic_hidden;
mod general_forum_topic_unhidden;
mod inline_keyboard_button;
mod inline_keyboard_markup;
mod inline_query;
mod invoice;
mod location;
mod login_url;
mod mask_position;
mod message;
mod message_auto_delete_timer_changed;
mod message_entity;
mod order_info;
mod passport_data;
mod passport_file;
mod photo_size;
mod poll;
mod poll_answer;
mod poll_option;
mod pre_checkout_query;
mod proximity_alert_triggered;
mod shipping_address;
mod shipping_query;
mod sticker;
mod successful_payment;
mod switch_inline_query_chosen_chat;
mod update;
mod user;
mod user_shared;
mod venue;
mod video;
mod video_chat_ended;
mod video_chat_participants_invited;
mod video_chat_scheduled;
mod video_chat_started;
mod video_note;
mod voice;
mod web_app_data;
mod web_app_info;
mod write_access_allowed;

pub use crate::animation::Animation;
pub use crate::audio::Audio;
pub use crate::callback_game::CallbackGame;
pub use crate::callback_query::CallbackQuery;
pub use crate::chat::Chat;
pub use crate::chat::ChatType;
pub use crate::chat_invite_link::ChatInviteLink;
pub use crate::chat_join_request::ChatJoinRequest;
pub use crate::chat_location::ChatLocation;
pub use crate::chat_member::ChatMember;
pub use crate::chat_member_updated::ChatMemberUpdated;
pub use crate::chat_permissions::ChatPermissions;
pub use crate::chat_photo::ChatPhoto;
pub use crate::chat_shared::ChatShared;
pub use crate::chosen_inline_result::ChosenInlineResult;
pub use crate::contact::Contact;
pub use crate::dice::Dice;
pub use crate::document::Document;
pub use crate::encrypted_credentials::EncryptedCredentials;
pub use crate::encrypted_passport_element::EncryptedPassportElement;
pub use crate::encrypted_passport_element::EncryptedPassportElementType;
pub use crate::file::File;
pub use crate::forum_topic_closed::ForumTopicClosed;
pub use crate::forum_topic_created::ForumTopicCreated;
pub use crate::forum_topic_edited::ForumTopicEdited;
pub use crate::forum_topic_reopened::ForumTopicReopened;
pub use crate::game::Game;
pub use crate::general_forum_topic_hidden::GeneralForumTopicHidden;
pub use crate::general_forum_topic_unhidden::GeneralForumTopicUnhidden;
pub use crate::inline_keyboard_button::InlineKeyboardButton;
pub use crate::inline_keyboard_markup::InlineKeyboardMarkup;
pub use crate::inline_query::InlineQuery;
pub use crate::invoice::Invoice;
pub use crate::location::Location;
pub use crate::login_url::LoginUrl;
pub use crate::mask_position::MaskPosition;
pub use crate::message::Message;
pub use crate::message_auto_delete_timer_changed::MessageAutoDeleteTimerChanged;
pub use crate::message_entity::MessageEntity;
pub use crate::message_entity::MessageEntityType;
pub use crate::order_info::OrderInfo;
pub use crate::passport_data::PassportData;
pub use crate::passport_file::PassportFile;
pub use crate::photo_size::PhotoSize;
pub use crate::poll::Poll;
pub use crate::poll::PollType;
pub use crate::poll_answer::PollAnswer;
pub use crate::poll_option::PollOption;
pub use crate::pre_checkout_query::PreCheckoutQuery;
pub use crate::proximity_alert_triggered::ProximityAlertTriggered;
pub use crate::shipping_address::ShippingAddress;
pub use crate::shipping_query::ShippingQuery;
pub use crate::sticker::Sticker;
pub use crate::sticker::StickerType;
pub use crate::successful_payment::SuccessfulPayment;
pub use crate::switch_inline_query_chosen_chat::SwitchInlineQueryChosenChat;
pub use crate::update::Update;
pub use crate::update::UpdateValue;
pub use crate::user::User;
pub use crate::user_shared::UserShared;
pub use crate::venue::Venue;
pub use crate::video::Video;
pub use crate::video_chat_ended::VideoChatEnded;
pub use crate::video_chat_participants_invited::VideoChatParticipantsInvited;
pub use crate::video_chat_scheduled::VideoChatScheduled;
pub use crate::video_chat_started::VideoChatStarted;
pub use crate::video_note::VideoNote;
pub use crate::voice::Voice;
pub use crate::web_app_data::WebAppData;
pub use crate::web_app_info::WebAppInfo;
pub use crate::write_access_allowed::WriteAccessAllowed;
